name: Problem or bug
description: Create a report to help us improve
labels: [ Potential bug, Verification ]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs or problems only!
        If you have a feature request or a question, please use one of the other templates.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues and no issue is describing my issue
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing. Tell us what you were trying to do and what happened.
        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: dropdown
    id: device
    validations:
      required: true
    attributes:
      label: With which model does the problem occur?
      options:
        - Deebot OZMO 920
        - Deebot OZMO 950
        - Deebot U2 series
        - Deebot N8 series
        - Deebot N9 series
        - Deebot N10 series
        - Deebot T8 series
        - Deebot T9 series
        - Deebot T10 series
        - Deebot T20 series
        - Deebot X1 series
        - Deebot X2 series
        - Other model (Please fill out the fields at the bottom of the form)
  - type: dropdown
    id: installation_source
    validations:
      required: true
    attributes:
      label: From which source you have installed the adapter?
      options:
        - Stable (default)
        - Beta (latest)
        - GitHub
        - Other (npm, custom)
      description: >
        Please make sure that you select the correct source.
        If you did not install the adapter manually (GitHub, npm, custom) and are still not sure, please check your ioBroker system settings.
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Version of the ioBroker adapter ("info.version")
      placeholder: e.g. 1.1.1, 1.2.2-alpha.1
      description: >
        See state "info.version" or "Adapter" tab
  - type: input
    id: library_version
    validations:
      required: true
    attributes:
      label: Version of the ecovacs-deebot.js library ("info.library.version")
      placeholder: e.g. 0.6.0, 0.6.1-beta.0
      description: >
        See state "info.library.version"
  - type: input
    id: jscontroller_version
    validations:
      required: true
    attributes:
      label: Version of the JS controller
      placeholder: e.g. 3.2.16, 3.3.15
      description: >
        See "Hosts" tab
  - type: input
    id: nodejs_version
    validations:
      required: true
    attributes:
      label: Version of Node.js
      placeholder: e.g. v10.23.0, v14.17.2
      description: >
        See "Info" Tab or use `node -v` via terminal
  - type: dropdown
    id: os
    validations:
      required: true
    attributes:
      label: Operating system
      options:
        - Linux
        - Windows
        - MacOS
        - Other
  - type: markdown
    attributes:
      value: |
        # Details / additional information
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful?
      description: >
        For example, error message, or stack traces
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
  - type: input
    id: otherDevice
    validations:
      required: false
    attributes:
      label: Which "other" models are you using?
      placeholder: Deebot [OZMO] xxx
      description: >
        Only needed if the model is not listed above ("With which model does the problem occur?") or if you use more than one model with this adapter
  - type: input
    id: deviceClass
    validations:
      required: false
    attributes:
      label: Ecovacs device class ("info.deviceClass")
      placeholder: e.g. 1zqysa
      description: >
        See "info.deviceClass".
        Only needed if you have selected "Other model" ("With which model does the problem occur?")
  - type: dropdown
    id: communicationProtocol
    validations:
      required: false
    attributes:
      label: Communication protocol ("info.library.communicationProtocol")
      options:
        - XMPP
        - MQTT
      description: >
        See "info.library.communicationProtocol".
        Only needed if you have selected "Other model" ("With which model does the problem occur?")
  - type: dropdown
    id: canvasModuleIsInstalled
    validations:
      required: false
    attributes:
      label: Is the canvas module installed? ("info.library.canvasModuleIsInstalled")
      options:
        - yes (true)
        - no (false)
        - irrelevant
      description: >
        Only needed if the problem is related to map- or position-related functions.
        See "info.library.canvasModuleIsInstalled".
