name: Question
description: Ask a question
labels: [ Question ]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for questions only!
        If you have a problem or a feature request, please use one of the other templates.
  - type: textarea
    validations:
      required: true
    attributes:
      label: The question
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: dropdown
    id: device
    validations:
      required: false
    attributes:
      label: Which model do you own?
      options:
        - Deebot OZMO 920
        - Deebot OZMO 950
        - Deebot U2 series
        - Deebot N8 series
        - Deebot N9 series
        - Deebot N10 series
        - Deebot T8 series
        - Deebot T9 series
        - Deebot T10 series
        - Deebot T20 series
        - Deebot X1 series
        - Deebot X2 series
        - Other model
  - type: input
    id: version
    validations:
      required: false
    attributes:
      label: Which version of the ioBroker adapter are you currently using?
      placeholder: e.g. 1.1.1, 1.2.2-alpha.1
      description: >
        See state "info.version" or "Adapter" tab
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
